### ISSUE TITLE
Error during building BLTG wallet for Mac OS

### ISSUE THREAD

**Issue by Rkrushanovskij** [Block-Logic-Technology-Group/bltg#1]
Hi! I`m trying to build wallet accord to guide https://github.com/Block-Logic-Technology-Group/bltg/blob/master/doc/build-osx.md

On step `make` it raises with error:
```
$ make
Making all in src
  CXX      bltgd-bltgd.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-blocksignature.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-leveldbwrapper.o
  CXX      libbitcoin_server_a-main.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-noui.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-rest.o
  CXX      libbitcoin_server_a-rpcblockchain.o
  CXX      libbitcoin_server_a-rpcmasternode.o
  CXX      libbitcoin_server_a-rpcmasternode-budget.o
  CXX      libbitcoin_server_a-rpcmining.o
  CXX      libbitcoin_server_a-rpcmisc.o
  CXX      libbitcoin_server_a-rpcnet.o
  CXX      libbitcoin_server_a-rpcrawtransaction.o
  CXX      libbitcoin_server_a-rpcserver.o
  CXX      script/libbitcoin_server_a-sigcache.o
  CXX      libbitcoin_server_a-sporkdb.o
  CXX      libbitcoin_server_a-timedata.o
  CXX      libbitcoin_server_a-torcontrol.o
  CXX      libbitcoin_server_a-txdb.o
  CXX      libbitcoin_server_a-txmempool.o
  CXX      libbitcoin_server_a-zbltgchain.o
  AR       libbitcoin_server.a
  CXX      libbitcoin_common_a-accumulators.o
accumulators.cpp:24:15: error: call to 'distance' is ambiguous
    int pos = distance(zerocoinDenomList.begin(), find(zerocoinDenomList.begin(), zerocoinDenomList.end(), denomination));
              ^~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:590:1: note: candidate function [with _InputIter = std::__1::__wrap_iter<const libzerocoin::CoinDenomination *>]
distance(_InputIter __first, _InputIter __last)
^
/usr/local/include/boost/iterator/distance.hpp:49:9: note: candidate function [with SinglePassIterator = std::__1::__wrap_iter<const libzerocoin::CoinDenomination *>]
        distance(SinglePassIterator first, SinglePassIterator last)
        ^
1 error generated.
make[2]: *** [libbitcoin_common_a-accumulators.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Environment: MacOS High Sierra 10.13.6

Could you please help me? I need `bltgd` functionality

**Comment by AJ5629** [comment]
If you’re setting up a BLTG Core – Wallet, there is a Max OS X dmg wallet downloadable from the Block-Logic Technology Group discord > new-wallets channel. 

 

Thanks and Regards,

Art Feggins

Office: +1 323 200-2150 || Mobile +66 (0) 92 347 2109

Block-Logic Technology Group Developer Advisor 

 

On 2/14/19, 20:44, "Rkrushanovskij" <notifications@github.com> wrote:

 

Hi! I`m trying to build wallet accord to guide https://github.com/Block-Logic-Technology-Group/bltg/blob/master/doc/build-osx.md

On step make it raises with error:
$ make
Making all in src
  CXX      bltgd-bltgd.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-blocksignature.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-leveldbwrapper.o
  CXX      libbitcoin_server_a-main.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-noui.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-rest.o
  CXX      libbitcoin_server_a-rpcblockchain.o
  CXX      libbitcoin_server_a-rpcmasternode.o
  CXX      libbitcoin_server_a-rpcmasternode-budget.o
  CXX      libbitcoin_server_a-rpcmining.o
  CXX      libbitcoin_server_a-rpcmisc.o
  CXX      libbitcoin_server_a-rpcnet.o
  CXX      libbitcoin_server_a-rpcrawtransaction.o
  CXX      libbitcoin_server_a-rpcserver.o
  CXX      script/libbitcoin_server_a-sigcache.o
  CXX      libbitcoin_server_a-sporkdb.o
  CXX      libbitcoin_server_a-timedata.o
  CXX      libbitcoin_server_a-torcontrol.o
  CXX      libbitcoin_server_a-txdb.o
  CXX      libbitcoin_server_a-txmempool.o
  CXX      libbitcoin_server_a-zbltgchain.o
  AR       libbitcoin_server.a
  CXX      libbitcoin_common_a-accumulators.o
accumulators.cpp:24:15: error: call to 'distance' is ambiguous
    int pos = distance(zerocoinDenomList.begin(), find(zerocoinDenomList.begin(), zerocoinDenomList.end(), denomination));
              ^~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:590:1: note: candidate function [with _InputIter = std::__1::__wrap_iter<const libzerocoin::CoinDenomination *>]
distance(_InputIter __first, _InputIter __last)
^
/usr/local/include/boost/iterator/distance.hpp:49:9: note: candidate function [with SinglePassIterator = std::__1::__wrap_iter<const libzerocoin::CoinDenomination *>]
        distance(SinglePassIterator first, SinglePassIterator last)
        ^
1 error generated.
make[2]: *** [libbitcoin_common_a-accumulators.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
Environment: MacOS High Sierra 10.13.6

Could you please help me? I need bltgd functionality

**Comment by Rkrushanovskij** [comment]
@AJ5629 Thanks for your answer! What if i need bltgd?

**Comment by AJ5629** [comment]
I’m not sure what you mead by bltgd? Please explain your issue further. I also recommend you post your questions in the Block-Logic Technology Group – Support channel.

 

Thanks and Regards,

Art Feggins

Office: +1 323 200-2150 || Mobile +66 (0) 92 347 2109

Block-Logic Technology Group Developer Advisor 

 

On 2/15/19, 14:24, "Rkrushanovskij" <notifications@github.com> wrote:

 

@AJ5629 Thanks for your answer! What if i need bltgd?

**Comment by Rkrushanovskij** [comment]
@AJ5629 Hmm. Ability to run daemon of wallet from command-line? https://github.com/Block-Logic-Technology-Group/bltg/blob/master/doc/build-osx.md#building-bltgd
