### ISSUE TITLE
bltg.conf file's "maxconnection" not being observed.

### ISSUE THREAD

**Issue by LinuxETC** [Block-Logic-Technology-Group/bltg#5]
Within the `.bltg/bltg.conf` file there is the variable `maxconnections` that could be used and set to establish a maximum number of connections to the wallet service/daemon.  

I am noticing this variable is NOT being observed unfortunately.  As a result, a MN's wallet can be flooded if not pseudo DoS due to excessive number of connections from other sources.

Please investigate and resolve.  Thanks in advance.

**Comment by cpass78** [comment]
Are you certain that is the config file being loaded? If you used the masternode script to install, the actual config file loaded is at /etc/masternodes/bltg_n#.conf

**Comment by LinuxETC** [comment]
Yes since I am not using another's "masternode script" to do the installations.

**Comment by cpass78** [comment]
Can't pinpoint the actual issue here. maxconnections is being respected in multiple wallets and no other issues have been reported. Recommend double checking the correct bltg.conf is being used.

Closing this for now.
